### ISSUE TITLE
Upgrading codebase for compatibility with Python 3

### ISSUE THREAD

**Issue by bmaluenda** [switch-model/switch#113]
Given recent issues with package installation ( #111 ) and the fact that Python 2 will cease to be maintained by January 1st, 2020, I propose we start planning for an upgrade to Python 3.

I haven't had experience with upgrading projects to be compatible with new versions of programming languages, so I'm not sure what the best approach for this work is:

-Should we tackle this by creating a new branch and upgrading one module at a time until everything is ready and then merge?
-Should we create one branch per module and merge one at a time (with backwards compatibility to avoid breaking Python 2 modules)?
-Should we divide tasks between us beforehand? Or just commit-as-much-as-you-can?
-Should we look for external help (maybe Mark or someone from the ERG)?

Happy to hear your thoughts on this. I can personally commit some hours per week to support this project (if this is something we want to embark upon).

**Comment by mfripp** [comment]
I'm actually working on this right now. We don't use a lot of Python 2 specific elements, so I'm hopeful I can post the whole thing as Switch 2.0.4 next week (not quite ready to jump to 2.1, since we just published the paper on 2.0 and this change won't actually change behavior at all).

**Comment by josiahjohnston** [comment]
Good suggestion, and great news! Please let us know if you need any help with that (like any complications or distractions). Otherwise, we can plan to review and integrate next week?

**Comment by mfripp** [comment]
There's a working pull request for Switch 2.0.4 with Python 3 compatibility now (#114). So we can move this discussion over to there now. Turned out to be a fairly straightforward upgrade, with just a few issues to track down. Hurray for careful coding and for our testing suite! It would be great to add more tests to get more complete coverage of model code and behavior in the future.
