### ISSUE TITLE
Python 3.0?

### ISSUE THREAD

**Issue by PascalLesage** [switch-model/switch#134]
I was wondering if there were plans to update to Python 3?
https://docs.python.org/3/howto/pyporting.html
If not, is there an appetite for such a move?

**Comment by mfripp** [comment]
Switch has run on Python 3 since version 2.0.4. Please see [here](https://github.com/switch-model/switch/releases) for a list of releases. The easiest way to install the latest release is via `conda` or `pip`, as described [here](https://github.com/switch-model/switch/blob/master/INSTALL.md).
