### ISSUE TITLE
Switch doesn't allow having zero existing builds

### ISSUE THREAD

**Issue by mseaborn** [switch-model/switch#24]
Switch currently requires there to be at least one existing build.

Steps to reproduce: Take `examples/copperplate0` and modify it by deleting all rows from `proj_existing_builds.tab` and `proj_build_costs.tab`.  Run switch_mod.solve.

Expected result: No error.

Actual result: Switch gives the following error:

```
ERROR: Constructing component 'proj_existing_cap' from data={None: 'PROJECT'} failed:
	RuntimeError: Failed to set value for param=proj_existing_cap, index=None, value=PROJECT.
		source error message="Error setting parameter value: Index 'None' is not valid for array Param 'proj_existing_cap'"
Traceback (most recent call last):
...
  File ".../pyomo/core/base/param.py", line 802, in construct
    % (self.cname(True), str(key), str(val), str(msg)) )
RuntimeError: Failed to set value for param=proj_existing_cap, index=None, value=PROJECT.
	source error message="Error setting parameter value: Index 'None' is not valid for array Param 'proj_existing_cap'"
```

I debugged this and I discovered that Pyomo has a dubious special case for 1-line `.tab` files.  (See the `elif len(tmp) == 1` case in `pyomo/core/plugins/data/text.py`.)

I would expect Pyomo to treat a 1-line file as containing no rows of data (just a row of headings).  However, instead Pyomo seems to be converting the file to the declaration `param proj_existing_cap := PROJECT`.

A possible fix would be to change `load_aug()` in `utilities.py` so that it skips any `.tab` files that contain zero rows.  `load_aug()` already has a check for that, but it's only enabled when it's called with `optional=True`.

**Comment by bmaluenda** [comment]
This was fixed by you in [this commit](https://github.com/switch-model/switch/commit/3b77568299505652c7e248011ea883543ab1b907) from August 17th, right Mark?

Could we close this Issue then? (I'm trying to clean up a bit) 
Sorry for not commenting when it was relevant, I missed this post.

**Comment by mseaborn** [comment]
Yes, this is fixed -- closing.  Thanks for the reminder.
