### ISSUE TITLE
Argument parser not correctly working

### ISSUE THREAD

**Issue by bmaluenda** [switch-model/switch#29]
If arguments that set options for the solve module are inputted in the command line along with the `python -m switch_mod.solve` command, then they are also passed to the model's `_ArgumentParser`, which aims to get command line options for other modules, raising an error since no module uses the option `verbose`, for example.

I think a way to get around this would be to modify the `define_AbstractModel()` and `create_model()` functions in the utilities module so their default values are empty lists, instead of all of the command line options: change `sys.argv[1:]` for `[]`. That way, the solve module will be able to parse the basic options and non of those will be passed to the model's module option parser.

If a developer is writing a new module which requires a command line option, then he can actually pass an argument list instead of leaving the default value.

An alternative would be to write some lines to filter the system's argument list for non-solve options and pass that list as the default.

I'm not sure what approach would be more suitable given pending pull request [https://github.com/switch-model/switch/pull/17]. Maybe defaulting to an empty list would be better in the very short term so that new users can get SWITCH working in their first run.

**Comment by mfripp** [comment]
I'm not sure I understand all the details of this, but it sounds like some code that depends on the scenario-solver branch may have leaked into the master branch. I think pull request #17 is ripe for merging and it's probably easier to do that then to keep working around it. Would that fix this problem?
