### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by bmaluenda** [switch-model/switch#39]
I have been pondering on the SWITCH git workflow and have some questions/comments:

Why are we always doing pull requests from branches in our own forks of the repo, instead of pushing our changes to a new branch in the same SWITCH repo and doing the pull request from there?

I think it would simplify the work flow, since it would be:

(Option 1) When your changes consist in several commits that make it easier to follow the history:

-Write changes / new features into a new branch of your local SWITCH repo
-Push them to a new branch in the switch_model repo
-Do a Pull Request from that new branch to the master branch
-Make changes/additions according to the peer review

Once everything is approved, then:
-If the master branch received new commits from someone else in the meantime:
    ----Pull them to your local repo
    ----Rebase the local master branch into your new_branch to get those commits in the past history of the branch
-Rebase your local new_branch into the local master branch to put your commits after the master's Head (and this way you avoid getting that extra Merge commit that only says "this is a merge" and get a linear history)
-Push your local master branch into the remote. I tested it and GitHub even recognizes that you included all changes from the Pull Request and automatically closes it tagging it as "merged". The master's branch history becomes linear, with the original commits, then the commits someone else made and then your new features.
-Delete the remote branch to avoid accumulating branches

(Option 2) When you are doing some small or very condensed changes, so only 1 commit is necessary to understand them:

-Write changes / new features into a new branch of your local SWITCH repo
-Push them to a new branch in the switch_model repo
-Do a Pull Request from that new branch to the master branch
-Make changes/additions according to the peer review

Once everything is approved, then:
-Merge and squash the changes into a single commit. This provides a linear history, makes it really easy for inexperienced Git users to include changes (I count myself in that group) and is really quick (only 1 click is necessary on the GitHub interface). I did this for my latest commits and the history remains linear and is effective for small changes.

What do you think about this workflow? I find this option very convenient, since I like experimenting with my Fork and then just manually writing the features I want to add into the main SWITCH repo files. It would be simple if I could just push that new branch and then directly do a Pull Request.

**Comment by josiahjohnston** [comment]
This sounds good to me for current contributors. We just ran into a problem of Matthias not being able to write to my pull request because it started in my personal repo. Most of our workflow would be easier if we made short-lived branches on the main repo for review purposes. We won't give write access to our repo publicly, so if someone we don't very well wants to make a pull request, they can initiate it from their personal repository. 

I haven't used the merge and squash feature before; that sounds useful. I'll try to play around with that soon. Personally, I'll likely stick with rebasing twice, since that handles all use cases, but I get how that adds an extra learning curve ... I only finished understanding that recently ..

One question: If the master has had commits during the review process, does merge & squash handle that ok or do you need to rebase first?

**Comment by bmaluenda** [comment]
I played with GitHub a bit and if those commits on the master have no conflicts with the new branch, then merge and squash just places a new commit with the new features on top of the master's head and there is **no need to rebase first**.
If there are conflicts, then the process gets a bit messier and you have to end up resolving them and merging with a traditional merge, according to GitHub's command line instructions. In that case, the best would be to **rebase twice while resolving conflicts** and then just push to master.

So, to begin concluding our discussion: 

- If "trusted" collaborators want to add changes, they should create a new branch in this main repo and do a Pull Request. Once they have confirmation from another collaborator to merge those changes, then they have to merge and squash the pull request.
- If new collaborators want to add changes, they must create a new branch in their own forked repos and folow the same procedure.
- If the new features involve heavy changes that will be easier to understand with more than 1 commit, then they must do a double rebase to preserve linearity in the history and all their commits.

Is that OK to you all? We could write these instructions down on some file (`git_workflow.txt` or something like that) so everybody is clear on them.

**Comment by bmaluenda** [comment]
It seems GitHub enabled a new option when merging Pull Requests, to automatically **merge and rebase** the branch. Details are [described here.](https://help.github.com/articles/about-pull-request-merges/#rebase-and-merge-your-pull-request-commits)

That should make merging changes a lot easier, since now it is possible to both merge & rebase and squash & commit through the web interface (which saves time and trouble for people who are more used to GUIs, such as me).

So, our discussion's conclusion should slightly change:

- If "trusted" collaborators want to add changes, they should create a new branch in this main repo (usually done by pushing their local branches to this remote) and do a Pull Request. Once they have confirmation from another collaborator to merge those changes, then they have to **squash and merge** the pull request.
If the new features involve heavy changes that will be easier to understand with more than 1 commit, then they can **merge and rebase** to keep the individual commits in the history.

- If new collaborators want to add changes, they must create a new branch in their own forked repos and follow the same procedure. Approval for the Pull Request must come from one of the admins.

If everybody is OK with this, I can write the git flow down so new contributors are clear on it.

**Comment by mfripp** [comment]
One addendum might be that we could use a fast-track approval process for pull requests that only affect a regional part of the repository. e.g., if something is added to switch.hawaii (in the master repo), then the pull request can get approved by switch administrator(s) who work on switch.hawaii, even if that's only one person.

**Comment by josiahjohnston** [comment]
Merge and rebase sounds like a nice GUI feature :) I like squash too, now that I've played with it a bit. 

Matthias, I agree about the need to streamline reviews for regional subdirectories.

Benjamin, I'd like to add one note at the beginning that the submitter needs to verify that run_tests.py works before they start the pull request. It's an important part of the checklist..

**Comment by josiahjohnston** [comment]
I'm closing this issue since the feature has been committed.
