### ISSUE TITLE
Sunk costs

### ISSUE THREAD

**Issue by bmaluenda** [switch-model/switch#92]
I just noticed that **transmission sunk costs** -the capital and fixed O&M costs of existing capacity- are not considered in the objective function. This is due to the `TX_BUILDS_IN_PERIOD` set not including builds indexed by 'Legacy'.
This is not a problem by itself, but it happens that the model does include **generation sunk costs** -the capital and fixed O&M costs of predetermined capacity-. If the model allowed for early decommissioning or mothballing, these costs would not be sunk, but we still haven't enabled those features.

So, for consistency, either Tx sunk costs should be included in the OF or Gen sunk costs should be excluded. Either way, both total costs and (total - sunk) costs should be reported on model exit.

**Comment by josiahjohnston** [comment]
Good catch. I posted a fix to your pull request #91, but we should port that to the master branch separately since it is a distinct bug fix, mostly unrelated to your new feature in that pull request.

**Comment by josiahjohnston** [comment]
Posted fix in pull request #96
